[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
exclude = '''
(
?pycache$
|\.pyi?
|.git
|.mypy_cache
|.pytest_cache
|.tox
|.venv
|_build
|buck-out
|build
|dist
)
'''

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true