@base_url = http://localhost:8000/api
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwODQ2NjE2MywiaWF0IjoxNzA4Mzc5NzYzLCJqdGkiOiJjMjg3YTZmZjE5MzY0MjE2OTYxOWY0ZmU1Y2MzZWUyZiIsInVzZXJfaWQiOjd9.vUhNuVhmfIDMaMzJPKrSI2zESrjepbyuM8-gJyCunns
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5MTk2MTczLCJpYXQiOjE3MDkxOTI1NzMsImp0aSI6IjM1ZDg3Yzg4MGM1ZTQ1NmRhNmMwNmI4NGEzZTU5YzI2IiwidXNlcl9pZCI6N30.OfbI_ienf-nXC4rtD2rChwgnNTP7TUy8T-Z-9NswhGI

# User Endpoints
POST {{base_url}}/users/register/
Content-Type: application/json

{"username": "nana", "password":  "testpass", "email": "user@example.com"}

###

POST {{base_url}}/users/login/
Content-Type: application/json

{"username": "name", "password":  "namepass123"}

###

POST {{base_url}}/users/token/refresh/
Content-Type: application/json

{"refresh": "{{refresh_token}}"}

###

POST {{base_url}}/users/token/verify/
Content-Type: application/json

{"token":  "{{access_token}}"}

###

# Event Endpoints
GET {{base_url}}/events/
Content-Type: application/json

###

# Create a new EVENT (POST request)
POST {{base_url}}/events/create/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "name": "for Denisa2",
    "description": "Morning Sunshine",
    "start_date": "2024-02-15T20:46:11Z",
    "end_date": "2024-02-17T20:46:16Z",
    "max_attendees": 5
}

###

GET {{base_url}}/events/owned/
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Retrieve Event Details (GET request)
GET {{base_url}}/events/6/
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Update an Event (PUT request) - not owner
PUT {{base_url}}/events/7/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Limited Event",
  "description": "Updated Description",
  "start_date": "2024-02-15T20:46:11Z",
  "end_date": "2024-02-17T20:46:16Z",
  "max_attendees": 1
}

###

# Update an Event (PUT request) - owner
PUT {{base_url}}/events/8/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Limited Event - Denisa",
  "description": "Updated Description",
  "start_date": "2024-02-15T20:46:11Z",
  "end_date": "2024-02-17T20:46:16Z",
  "max_attendees": 2
}

###

# Delete an Event (DELETE request)
DELETE {{base_url}}/events/6/
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Register to an Event (POST request) - max out
POST {{base_url}}/events/5/register/
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Register to an Event (POST request) - 200
POST {{base_url}}/events/8/register/
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Unregister from an Event (POST request) - not registered
DELETE {{base_url}}/events/5/unregister/
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Unregister from an Event (POST request) - 200
DELETE {{base_url}}/events/8/unregister/
Content-Type: application/json
Authorization: Bearer {{access_token}}
