# Generated by Django 5.0.2 on 2024-02-20 06:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 22, 6, 17, 42, 491103, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
